const categories = [
  {
    id: 1,
    name: "Motoryzacja",
    subcategories: ["Samochody osobowe", "Motocykle", "Części", "Przyczepy", "Samochody Ciężarowe", "Inne pojazdy"],
    subsubcategories: {
      Części: [
        "Silnik i układ napędowy",
        "Hamulce",
        "Zawieszenie",
        "Elektryka",
        "Karoseria",
        "Wnętrze",
        "Opony i felgi",
        "Pozostałe",
      ],
      Przyczepy: ["Przyczepy osobowe", "Przyczepy towarowe", "Przyczepy kempingowe", "Naczepy"],
      "Inne pojazdy": ["Quady", "Skutery", "Rowery elektryczne", "Łodzie", "Maszyny rolnicze", "Maszyny budowlane"],
    },
    fields: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Aixam",
          "Alfa Romeo",
          "Aston Martin",
          "Audi",
          "Bentley",
          "BMW",
          "Cadillac",
          "Chevrolet",
          "Chrysler",
          "Citroën",
          "Dacia",
          "Daewoo",
          "Daihatsu",
          "Dodge",
          "Ferrari",
          "Fiat",
          "Ford",
          "Honda",
          "Hummer",
          "Hyundai",
          "Infiniti",
          "Jaguar",
          "Jeep",
          "Kia",
          "Lamborghini",
          "Lancia",
          "Land Rover",
          "Lexus",
          "Lincoln",
          "Maserati",
          "Mazda",
          "McLaren",
          "Mercedes-Benz",
          "Mini",
          "Mitsubishi",
          "Nissan",
          "Opel",
          "Peugeot",
          "Polonez",
          "Pontiac",
          "Porsche",
          "Renault",
          "Rolls-Royce",
          "Rover",
          "Saab",
          "Seat",
          "Škoda",
          "Smart",
          "SsangYong",
          "Subaru",
          "Suzuki",
          "Syrena",
          "Tata",
          "Tesla",
          "Toyota",
          "Trabant",
          "Volkswagen",
          "Volvo",
          "Warszawa",
          "Wartburg",
          "Wołga",
          "Pozostałe",
        ],
        conditionalOptions: {
          "Samochody Ciężarowe": [
            "Isuzu",
            "Iveco",
            "Mercedes-Benz",
            "Ford",
            "Volkswagen",
            "MAN",
            "DAF",
            "Renault",
            "Scania",
            "Volvo",
            "Pozostałe",
          ],
          Motocykle: [
            "Aprilia",
            "BMW",
            "Ducati",
            "Harley-Davidson",
            "Honda",
            "Kawasaki",
            "KTM",
            "Suzuki",
            "Triumph",
            "Yamaha",
            "Pozostałe",
          ],
          "Samochody osobowe": [
            "Aixam",
            "Alfa Romeo",
            "Aston Martin",
            "Audi",
            "Bentley",
            "BMW",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroën",
            "Dacia",
            "Daewoo",
            "Daihatsu",
            "Dodge",
            "Ferrari",
            "Fiat",
            "Ford",
            "Honda",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Jaguar",
            "Jeep",
            "Kia",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Lexus",
            "Lincoln",
            "Maserati",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mini",
            "Mitsubishi",
            "Nissan",
            "Opel",
            "Peugeot",
            "Polonez",
            "Pontiac",
            "Porsche",
            "Renault",
            "Rolls-Royce",
            "Rover",
            "Saab",
            "Seat",
            "Škoda",
            "Smart",
            "SsangYong",
            "Subaru",
            "Suzuki",
            "Syrena",
            "Tata",
            "Tesla",
            "Toyota",
            "Trabant",
            "Volkswagen",
            "Volvo",
            "Warszawa",
            "Wartburg",
            "Wołga",
            "Pozostałe",
          ],
          Przyczepy: ["Niewiadów", "Tema", "Unitrailer", "Brenderup", "Pozostałe"],
          "Inne pojazdy": ["Yamaha", "Honda", "Kawasaki", "Can-Am", "Polaris", "Pozostałe"],
        },
        required: true,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: true, dbField: "year" },
      { name: "przebieg", label: "Przebieg (km)", type: "number", required: true, dbField: "mileage" },
      { name: "pojemnosc", label: "Pojemność silnika (cm³)", type: "number", required: true, dbField: "engine_size" },
      {
        name: "paliwo",
        label: "Rodzaj paliwa",
        type: "select",
        options: ["Benzyna", "Diesel", "LPG", "Elektryczny", "Hybryda"],
        required: true,
        dbField: "fuel_type",
      },
      {
        name: "skrzynia",
        label: "Skrzynia biegów",
        type: "select",
        options: ["Manualna", "Automatyczna"],
        required: false,
        dbField: "transmission",
      },
      {
        name: "kolor",
        label: "Kolor",
        type: "select",
        options: [
          "Biały",
          "Czarny",
          "Srebrny",
          "Szary",
          "Czerwony",
          "Niebieski",
          "Zielony",
          "Żółty",
          "Brązowy",
          "Inny",
        ],
        required: false,
        dbField: "color",
      },
    ],
  },
  {
    id: 2,
    name: "RTV/AGD",
    subcategories: [
      "Telewizory",
      "Kamery",
      "Pralki/Suszarki",
      "Zmywarki",
      "Kuchenki",
      "Piekarniki",
      "Lodówki",
      "Zamrażarki",
      "Pozostałe",
    ],
    subsubcategories: {
      Pozostałe: ["Odkurzacze", "Żelazka", "Ekspresy do kawy", "Blendery", "Mikrofale", "Tostery", "Inne urządzenia"],
    },
    fields: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        conditionalOptions: {
          Telewizory: [
            "Samsung",
            "LG",
            "Sony",
            "Panasonic",
            "Philips",
            "Toshiba",
            "Sharp",
            "Grundig",
            "Hitachi",
            "Thomson",
            "Xiaomi",
            "Hisense",
            "TCL",
            "JVC",
            "Blaupunkt",
          ],
          Kamery: [
            "Sony",
            "Panasonic",
            "Canon",
            "Nikon",
            "GoPro",
            "DJI",
            "JVC",
            "Blackmagic",
            "Olympus",
            "Fujifilm",
            "Akaso",
            "YI",
            "Kodak",
            "SJCAM",
          ],
          "Pralki/Suszarki": [
            "Bosch",
            "Siemens",
            "Electrolux",
            "Samsung",
            "LG",
            "Whirlpool",
            "Amica",
            "Beko",
            "Indesit",
            "Candy",
            "Gorenje",
            "Hoover",
            "Hotpoint",
            "Miele",
          ],
          Zmywarki: [
            "Bosch",
            "Siemens",
            "Electrolux",
            "Whirlpool",
            "Beko",
            "Samsung",
            "Amica",
            "Indesit",
            "Candy",
            "Hotpoint",
            "Gorenje",
            "Miele",
            "Zanussi",
          ],
          Kuchenki: [
            "Amica",
            "Bosch",
            "Electrolux",
            "Whirlpool",
            "Samsung",
            "Beko",
            "Gorenje",
            "Indesit",
            "Candy",
            "Hotpoint",
            "Mastercook",
            "Mora",
          ],
          Piekarniki: [
            "Bosch",
            "Samsung",
            "Electrolux",
            "Whirlpool",
            "Beko",
            "Amica",
            "Siemens",
            "Gorenje",
            "Indesit",
            "Candy",
            "Hotpoint",
            "Teka",
          ],
          Lodówki: [
            "Samsung",
            "LG",
            "Bosch",
            "Electrolux",
            "Whirlpool",
            "Beko",
            "Amica",
            "Gorenje",
            "Indesit",
            "Candy",
            "Miele",
            "Hisense",
            "Haier",
          ],
          Zamrażarki: [
            "Electrolux",
            "Bosch",
            "Beko",
            "Whirlpool",
            "Amica",
            "Gorenje",
            "Liebherr",
            "Samsung",
            "Indesit",
            "Candy",
            "Hotpoint",
            "Haier",
          ],
          Pozostałe: [
            "Bosch",
            "Philips",
            "Tefal",
            "Braun",
            "Zelmer",
            "Moulinex",
            "Severin",
            "Russell Hobbs",
            "Amica",
            "Ravanson",
            "Clatronic",
            "Götze & Jensen",
          ],
        },
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
      { name: "rok_produkcji", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
    ],
  },
  {
    id: 3,
    name: "Elektronika",
    subcategories: ["Telefony i Akcesoria", "Komputery i Akcesoria", "Zegarki i Smartwache"],
    subsubcategories: {
      "Telefony i Akcesoria": ["Smartfony", "Urządzenia Stacjonarne", "Akcesoria"],
      "Komputery i Akcesoria": [
        "Komputery Stacjonarne",
        "Laptopy/Netbooki",
        "Tablety/Palmtopy",
        "Monitory/Projektory",
        "Drukarki/Skanery",
        "Akcesoria",
        "Internet i Sieci",
        "Oprogramowanie",
      ],
      "Zegarki i Smartwache": ["Smartwatche", "Zegarki klasyczne", "Zegarki sportowe"],
    },
    fields: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Alcatel",
          "Apple",
          "Asus",
          "BlackBerry",
          "HTC",
          "Huawei",
          "Lenovo",
          "LG",
          "Motorola",
          "Nokia",
          "Samsung",
          "Sony",
          "Sony Ericsson",
          "Xiaomi",
          "Pozostałe",
        ],
        conditionalOptions: {
          Smartfony: [
            "Alcatel",
            "Apple",
            "Asus",
            "BlackBerry",
            "HTC",
            "Huawei",
            "Lenovo",
            "LG",
            "Motorola",
            "Nokia",
            "Samsung",
            "Sony",
            "Sony Ericsson",
            "Xiaomi",
            "OnePlus",
            "Google",
            "Pozostałe",
          ],
          "Urządzenia Stacjonarne": ["Apple", "Dell", "HP", "Lenovo", "Acer", "Asus", "Microsoft"],
          "Komputery Stacjonarne": [
            "Acer",
            "Apple",
            "Asus",
            "Dell",
            "HP",
            "Huawei",
            "Lenovo",
            "Microsoft",
            "Samsung",
            "Sony",
            "Toshiba",
            "Inne marki",
          ],
          "Laptopy/Netbooki": [
            "Acer",
            "Apple",
            "Asus",
            "Dell",
            "HP",
            "Huawei",
            "Lenovo",
            "Microsoft",
            "Samsung",
            "Sony",
            "Toshiba",
            "Inne marki",
          ],
          "Tablety/Palmtopy": [
            "Acer",
            "Apple",
            "Asus",
            "Dell",
            "HP",
            "Huawei",
            "Lenovo",
            "Microsoft",
            "Samsung",
            "Sony",
            "Toshiba",
            "Inne marki",
          ],
          "Monitory/Projektory": [
            "Acer",
            "Apple",
            "Asus",
            "Dell",
            "HP",
            "Huawei",
            "Lenovo",
            "Microsoft",
            "Samsung",
            "Sony",
            "Toshiba",
            "Inne marki",
          ],
          "Drukarki/Skanery": [
            "Acer",
            "Apple",
            "Asus",
            "Dell",
            "HP",
            "Huawei",
            "Lenovo",
            "Microsoft",
            "Samsung",
            "Sony",
            "Toshiba",
            "Inne marki",
          ],
          Akcesoria: [
            "Logitech",
            "Microsoft",
            "Razer",
            "Corsair",
            "SteelSeries",
            "Asus",
            "Acer",
            "Dell",
            "HP",
            "Lenovo",
            "Inne marki",
          ],
          Smartwatche: ["Apple", "Samsung", "Huawei", "Garmin", "Fitbit", "Amazfit", "Polar", "Suunto"],
          "Zegarki klasyczne": ["Rolex", "Omega", "Seiko", "Citizen", "Casio", "Tissot", "TAG Heuer", "Breitling"],
          "Zegarki sportowe": ["Garmin", "Polar", "Suunto", "Casio", "Timex"],
        },
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
      { name: "rok_produkcji", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
    ],
  },
  {
    id: 4,
    name: "Moda",
    subcategories: ["Kobiety", "Mężczyźni"],
    subsubcategories: {
      Kobiety: [
        "Sukienki",
        "Spódnice",
        "Bluzki i Koszule",
        "Swetry i Bluzy",
        "T-shirty i Toppi",
        "Marynarki i Żakiety",
        "Kurtki i Płaszcze",
        "Spodnie i Legginsy",
        "Buty",
        "Torebki",
        "Bielizna",
        "Stroje Kąpielowe",
        "Biżuteria",
        "Akcesoria (czapki, szaliki, rękawiczki)",
        "Pozostałe",
      ],
      Mężczyźni: [
        "Koszule",
        "T-shirty i Polówki",
        "Swetry i Bluzy",
        "Marynarki i Garnitury",
        "Kurtki i Płaszcze",
        "Spodnie i Jeansy",
        "Buty",
        "Bielizna",
        "Zegarki",
        "Paski i Portfele",
        "Akcesoria (czapki, szaliki, rękawiczki)",
        "Pozostałe",
      ],
    },
    fields: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "34", "36", "38", "40", "42", "44", "46", "48"],
        conditionalOptions: {
          Buty: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48"],
        },
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
    ],
  },
  {
    id: 5,
    name: "Dom i ogród",
    subcategories: ["Meble do domu", "Wyposażenie domu", "Narzędzia", "Budownictwo", "Wyposażenie Ogrodu", "Inne"],
    subsubcategories: {
      "Meble do domu": [
        "Sofy i fotele",
        "Stoły i krzesła",
        "Szafy i komody",
        "Łóżka i materace",
        "Meble kuchenne",
        "Meble łazienkowe",
        "Pozostałe meble",
      ],
      "Wyposażenie domu": [
        "Oświetlenie",
        "Dywany i wykładziny",
        "Zasłony i firany",
        "Dekoracje",
        "Naczynia i sztućce",
        "Pościel i ręczniki",
      ],
      Narzędzia: ["Narzędzia elektryczne", "Narzędzia ręczne", "Narzędzia ogrodowe", "Maszyny i urządzenia"],
      "Wyposażenie Ogrodu": [
        "Meble ogrodowe",
        "Grille i akcesoria",
        "Rośliny i nasiona",
        "Donice i osłonki",
        "Narzędzia ogrodowe",
        "Oświetlenie ogrodowe",
      ],
    },
    fields: [
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
      { name: "wymiary", label: "Wymiary (cm)", type: "text", required: false, dbField: "dimensions" },
    ],
  },
  {
    id: 6,
    name: "Nieruchomości",
    subcategories: ["Na sprzedaż", "Wynajem", "Wynajem krótkoterminowy"],
    subsubcategories: {
      "Na sprzedaż": ["Domy", "Mieszkania", "Działki", "Lokale", "Garaże/Magazyny"],
      Wynajem: ["Domy", "Mieszkania", "Działki", "Lokale", "Garaże/Magazyny"],
      "Wynajem krótkoterminowy": ["Domy", "Mieszkania", "Działki", "Lokale", "Garaże/Magazyny"],
    },
    fields: [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      { name: "liczba_pokoi", label: "Liczba pokoi", type: "number", required: false, dbField: "rooms" },
      { name: "pietro", label: "Piętro", type: "number", required: false, dbField: "floor" },
      { name: "rok_budowy", label: "Rok budowy", type: "number", required: false, dbField: "year_built" },
      { name: "umeblowane", label: "Umeblowane", type: "checkbox", required: false, dbField: "has_balcony" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: [
          "Do remontu",
          "Do odświeżenia",
          "Do zamieszkania",
          "Stan deweloperski",
          "Stan surowy otwarty",
          "Stan surowy zamknięty",
          "Po generalnym remoncie",
        ],
        required: true,
        dbField: "condition_type",
      },
    ],
  },
  {
    id: 7,
    name: "Dla dzieci",
    subcategories: ["Ubranka", "Zabawki", "Zdrowie i Higiena", "Akcesoria", "Artykuły Szkolne", "Inne"],
    subsubcategories: {
      Ubranka: ["0-3 miesiące", "3-6 miesięcy", "6-12 miesięcy", "1-2 lata", "2-4 lata", "4-8 lat", "8-14 lat"],
      Zabawki: [
        "Zabawki dla niemowląt",
        "Klocki i puzzle",
        "Lalki i akcesoria",
        "Samochodziki i pojazdy",
        "Gry planszowe",
        "Zabawki edukacyjne",
        "Zabawki elektroniczne",
      ],
      Akcesoria: [
        "Wózki dziecięce",
        "Foteliki samochodowe",
        "Łóżeczka i materace",
        "Krzesełka do karmienia",
        "Nosidełka",
      ],
    },
    fields: [
      { name: "wiek", label: "Wiek dziecka (lata)", type: "number", required: false, dbField: "child_age" },
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: [
          "50",
          "56",
          "62",
          "68",
          "74",
          "80",
          "86",
          "92",
          "98",
          "104",
          "110",
          "116",
          "122",
          "128",
          "134",
          "140",
          "146",
          "152",
        ],
        required: false,
        dbField: "size",
      },
    ],
  },
  {
    id: 8,
    name: "Zdrowie i Uroda",
    subcategories: [
      "Perfumy",
      "Kosmetyki",
      "Makijaż",
      "Apteczka",
      "Akcesoria",
      "Pielęgnacja",
      "Usługi Kosmetyczne",
      "Usługi Fryzjerskie",
      "Pozostałe",
    ],
    subsubcategories: {
      Kosmetyki: ["Pielęgnacja twarzy", "Pielęgnacja ciała", "Pielęgnacja włosów", "Kosmetyki naturalne"],
      Makijaż: ["Podkłady i korektory", "Cienie i eyelinery", "Szminki i błyszczyki", "Pędzle i akcesoria"],
      Akcesoria: ["Szczotki i grzebienie", "Suszarki i prostownice", "Masażery", "Inne akcesoria"],
    },
    fields: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      { name: "rozmiar", label: "Rozmiar/Pojemność", type: "text", required: false, dbField: "size" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "data_waznosci", label: "Data ważności", type: "text", required: false, dbField: "expiry_date" },
      {
        name: "typ_skory",
        label: "Typ skóry",
        type: "select",
        options: ["Normalna", "Sucha", "Tłusta", "Mieszana", "Wrażliwa", "Wszystkie typy"],
        required: false,
        dbField: "skin_type",
      },
    ],
  },
  {
    id: 9,
    name: "Zwierzęta i Akcesoria",
    subcategories: ["Psy", "Koty", "Ptaki", "Ryby i akwaria", "Gryzonie", "Gady", "Konie", "Pozostałe zwierzęta"],
    subsubcategories: {
      Psy: [
        "Szczenięta na sprzedaż",
        "Dorosłe psy na sprzedaż",
        "Karma i przysmaki",
        "Akcesoria dla psów",
        "Ubranka dla psów",
      ],
      Koty: [
        "Kocięta na sprzedaż",
        "Dorosłe koty na sprzedaż",
        "Karma i przysmaki",
        "Akcesoria dla kotów",
        "Żwirek i higiena",
      ],
      "Ryby i akwaria": [
        "Ryby słodkowodne",
        "Ryby morskie",
        "Akwaria i wyposażenie",
        "Rośliny akwariowe",
        "Karma dla ryb",
      ],
    },
    fields: [
      {
        name: "wiek",
        label: "Wiek zwierzęcia",
        type: "select",
        options: ["Młode (do 1 roku)", "Dorosłe (1-7 lat)", "Starsze (powyżej 7 lat)"],
        required: false,
        dbField: "pet_age",
      },
      {
        name: "rasa",
        label: "Rasa",
        type: "text",
        required: false,
        dbField: "breed",
      },
      {
        name: "plec",
        label: "Płeć",
        type: "select",
        options: ["Samiec", "Samica"],
        required: false,
        dbField: "gender",
      },
      {
        name: "szczepienia",
        label: "Szczepienia",
        type: "checkbox",
        required: false,
        dbField: "vaccinated",
      },
      {
        name: "rodowod",
        label: "Rodowód",
        type: "checkbox",
        required: false,
        dbField: "pedigree",
      },
    ],
  },
  {
    id: 10,
    name: "Praca",
    subcategories: ["Zdalna", "Stacjonarnie"],
    subsubcategories: {
      Zdalna: ["Umowa o Pracę", "B2B", "Umowa Zlecenie", "Umowa o dzieło", "Freelance"],
      Stacjonarnie: ["Umowa o Pracę", "B2B", "Umowa Zlecenie", "Umowa o dzieło", "Staż/Praktyki"],
    },
    fields: [
      { name: "stanowisko", label: "Stanowisko", type: "text", required: true, dbField: "position" },
      { name: "firma", label: "Firma", type: "text", required: false, dbField: "company" },
      {
        name: "rodzaj_umowy",
        label: "Rodzaj umowy",
        type: "select",
        options: ["Umowa o pracę", "Zlecenie", "Dzieło", "B2B", "Staż/Praktyki"],
        required: false,
        dbField: "contract_type",
      },
      { name: "wynagrodzenie", label: "Wynagrodzenie (PLN)", type: "number", required: false, dbField: "salary" },
      {
        name: "wymiar_pracy",
        label: "Wymiar pracy",
        type: "select",
        options: ["Pełny etat", "Część etatu", "Zlecenie", "Tymczasowa"],
        required: false,
        dbField: "work_time",
      },
      {
        name: "doswiadczenie",
        label: "Wymagane doświadczenie",
        type: "select",
        options: ["Brak wymagań", "Do 1 roku", "1-3 lata", "3-5 lat", "Powyżej 5 lat"],
        required: false,
        dbField: "experience_required",
      },
    ],
  },
  {
    id: 11,
    name: "Sport/Turystyka",
    subcategories: [
      "Rowery i Akcesoria",
      "Turystyka",
      "Siłownia/Fitness",
      "Wedkarstwo",
      "Bieganie",
      "Militaria",
      "Pozostałe",
    ],
    subsubcategories: {
      "Rowery i Akcesoria": [
        "Rowery górskie",
        "Rowery szosowe",
        "Rowery miejskie",
        "Rowery elektryczne",
        "Akcesoria rowerowe",
      ],
      Turystyka: ["Namioty", "Śpiwory", "Plecaki turystyczne", "Buty trekkingowe", "Odzież turystyczna"],
      "Siłownia/Fitness": ["Sprzęt siłowy", "Cardio", "Akcesoria fitness", "Odżywki"],
    },
    fields: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "rozmiar", label: "Rozmiar", type: "text", required: false, dbField: "size" },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "rok_produkcji", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
    ],
  },
  {
    id: 12,
    name: "Bilety/e-Bilety",
    subcategories: ["Koncerty", "Teatr/Opera", "Sport", "Kino", "Festiwale", "Konferencje", "Pozostałe wydarzenia"],
    subsubcategories: {
      Koncerty: ["Pop/Rock", "Klasyczna", "Jazz", "Elektroniczna", "Hip-hop/Rap", "Pozostałe"],
      Sport: ["Piłka nożna", "Koszykówka", "Siatkówka", "Tenis", "Boks/MMA", "Pozostałe sporty"],
    },
    fields: [
      { name: "wydarzenie", label: "Nazwa wydarzenia", type: "text", required: true, dbField: "event_name" },
      { name: "data_wydarzenia", label: "Data wydarzenia", type: "text", required: true, dbField: "event_date" },
      { name: "miejsce", label: "Miejsce wydarzenia", type: "text", required: true, dbField: "venue" },
      { name: "liczba_biletow", label: "Liczba biletów", type: "number", required: true, dbField: "ticket_count" },
      {
        name: "typ_biletu",
        label: "Typ biletu",
        type: "select",
        options: ["Normalny", "Ulgowy", "VIP", "Sektor stojący", "Sektor siedzący"],
        required: false,
        dbField: "ticket_type",
      },
    ],
  },
  {
    id: 13,
    name: "Usługi",
    subcategories: ["Lokalne", "Internetowe"],
    subsubcategories: {
      Lokalne: [
        "Dolnośląskie",
        "Kujawsko-Pomorskie",
        "Lubelskie",
        "Lubuskie",
        "Łódzkie",
        "Małopolskie",
        "Mazowieckie",
        "Opolskie",
        "Podkarpackie",
        "Podlaskie",
        "Pomorskie",
        "Śląskie",
        "Świętokrzyskie",
        "Warmińsko-Mazurskie",
        "Wielkopolskie",
        "Zachodniopomorskie",
      ],
      Internetowe: ["Programowanie", "Grafika i design", "Marketing", "Tłumaczenia", "Pisanie tekstów", "Pozostałe"],
    },
    fields: [
      { name: "nazwa_uslugi", label: "Nazwa usługi", type: "text", required: true, dbField: "service_name" },
      { name: "firma", label: "Firma", type: "text", required: false, dbField: "company" },
      {
        name: "cena_za_godzine",
        label: "Cena za godzinę (PLN)",
        type: "number",
        required: false,
        dbField: "hourly_rate",
      },
      {
        name: "dostepnosc",
        label: "Dostępność",
        type: "select",
        options: ["Od zaraz", "W ciągu tygodnia", "W ciągu miesiąca", "Do uzgodnienia"],
        required: false,
        dbField: "availability",
      },
      {
        name: "doswiadczenie",
        label: "Doświadczenie",
        type: "select",
        options: ["Początkujący", "Średnio zaawansowany", "Zaawansowany", "Ekspert"],
        required: false,
        dbField: "experience_level",
      },
    ],
  },
  {
    id: 14,
    name: "Przemysł",
    subcategories: ["Gastronomia", "Hotelarstwo", "Fryzjerstwo/Kosmetyka", "Biuro i Reklama", "Pozostałe"],
    subsubcategories: {
      Gastronomia: ["Wyposażenie kuchni", "Meble gastronomiczne", "Urządzenia chłodnicze", "Pozostałe"],
      "Biuro i Reklama": ["Meble biurowe", "Sprzęt biurowy", "Materiały reklamowe", "Drukarki i kopiarki"],
    },
    fields: [
      { name: "firma", label: "Firma", type: "text", required: false, dbField: "company" },
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      { name: "model", label: "Model", type: "text", required: false, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "rok_produkcji", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
    ],
  },
  {
    id: 15,
    name: "Rozrywka",
    subcategories: ["Filmy", "Muzyka", "Książki/Komiksy", "Gry", "Instrumenty", "Pozostałe"],
    subsubcategories: {
      Filmy: ["DVD", "Blu-ray", "VHS", "Filmy cyfrowe"],
      Muzyka: ["CD", "Winyle", "Kasety", "Muzyka cyfrowa"],
      "Książki/Komiksy": ["Literatura piękna", "Literatura faktu", "Podręczniki", "Komiksy", "Książki dla dzieci"],
      Gry: ["Gry PC", "PlayStation", "Xbox", "Nintendo", "Gry planszowe"],
      Instrumenty: ["Gitary", "Pianina/Keyboardy", "Perkusja", "Instrumenty dęte", "Pozostałe instrumenty"],
    },
    fields: [
      { name: "tytul", label: "Tytuł", type: "text", required: true, dbField: "title" },
      { name: "autor_wykonawca", label: "Autor/Wykonawca", type: "text", required: false, dbField: "author" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "rok_wydania", label: "Rok wydania", type: "number", required: false, dbField: "year" },
      {
        name: "format",
        label: "Format",
        type: "select",
        options: ["CD", "DVD", "Blu-ray", "Winyl", "Kaseta", "Cyfrowy", "Inny"],
        required: false,
        dbField: "format",
      },
    ],
  },
  {
    id: 16,
    name: "Antyki/Kolekcje/Sztuka",
    subcategories: ["Design/Antyki", "Kolekcje", "Hobby", "Pozostałe"],
    subsubcategories: {
      "Design/Antyki": [
        "Meble antyczne",
        "Porcelana i ceramika",
        "Obrazy i grafiki",
        "Biżuteria antyczna",
        "Zegary antyczne",
      ],
      Kolekcje: ["Monety", "Znaczki", "Pocztówki", "Militaria", "Samochodziki", "Figurki"],
      Hobby: ["Modelarstwo", "Filatelistyka", "Numizmatyka", "Pozostałe hobby"],
    },
    fields: [
      { name: "nazwa_przedmiotu", label: "Nazwa przedmiotu", type: "text", required: true, dbField: "item_name" },
      { name: "okres", label: "Okres/Epoka", type: "text", required: false, dbField: "period" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
      {
        name: "stan",
        label: "Stan zachowania",
        type: "select",
        options: ["Doskonały", "Bardzo dobry", "Dobry", "Zadowalający", "Wymaga renowacji"],
        required: true,
        dbField: "condition_type",
      },
      { name: "pochodzenie", label: "Pochodzenie", type: "text", required: false, dbField: "origin" },
      { name: "wymiary", label: "Wymiary", type: "text", required: false, dbField: "dimensions" },
    ],
  },
  {
    id: 17,
    name: "Wycieczki/Podróże",
    subcategories: ["Krajowe", "Zagraniczne"],
    subsubcategories: {
      Krajowe: ["Morze", "Góry", "Mazury", "Pozostałe Regiony"],
      Zagraniczne: ["Europa", "Azja", "Ameryka", "Afryka", "Australia/Oceania"],
    },
    fields: [
      { name: "destynacja", label: "Destynacja", type: "text", required: true, dbField: "destination" },
      { name: "data_wyjazdu", label: "Data wyjazdu", type: "text", required: true, dbField: "departure_date" },
      { name: "data_powrotu", label: "Data powrotu", type: "text", required: true, dbField: "return_date" },
      { name: "liczba_osob", label: "Liczba osób", type: "number", required: true, dbField: "person_count" },
      {
        name: "typ_noclegu",
        label: "Typ noclegu",
        type: "select",
        options: ["Hotel", "Pensjonat", "Apartament", "Camping", "Hostel", "Inne"],
        required: false,
        dbField: "accommodation_type",
      },
      {
        name: "wyzywianie",
        label: "Wyżywienie",
        type: "select",
        options: ["Brak", "Śniadania", "Śniadania i obiadokolacje", "All inclusive"],
        required: false,
        dbField: "meals_included",
      },
      { name: "transport", label: "Transport", type: "text", required: false, dbField: "transport" },
    ],
  },
]

export default categories
