// Definicja pól zależnych od kategorii i sub-subcategorii
export const categorySpecificFields: Record<string, Record<string, any[]>> = {
  Motoryzacja: {
    "Samochody osobowe": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Aixam",
          "Alfa Romeo",
          "Aston Martin",
          "Audi",
          "Bentley",
          "BMW",
          "Cadillac",
          "Chevrolet",
          "Chrysler",
          "Citroën",
          "Dacia",
          "Daewoo",
          "Daihatsu",
          "Dodge",
          "Ferrari",
          "Fiat",
          "Ford",
          "Honda",
          "Hummer",
          "Hyundai",
          "Infiniti",
          "Jaguar",
          "Jeep",
          "Kia",
          "Lamborghini",
          "Lancia",
          "Land Rover",
          "Lexus",
          "Lincoln",
          "Maserati",
          "Mazda",
          "McLaren",
          "Mercedes-Benz",
          "Mini",
          "Mitsubishi",
          "Nissan",
          "Opel",
          "Peugeot",
          "Polonez",
          "Pontiac",
          "Porsche",
          "Renault",
          "Rolls-Royce",
          "Rover",
          "Saab",
          "Seat",
          "Škoda",
          "Smart",
          "SsangYong",
          "Subaru",
          "Suzuki",
          "Syrena",
          "Tata",
          "Tesla",
          "Toyota",
          "Trabant",
          "Volkswagen",
          "Volvo",
          "Warszawa",
          "Wartburg",
          "Wołga",
          "Pozostałe",
        ],
        required: true,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: true, dbField: "year" },
      { name: "przebieg", label: "Przebieg (km)", type: "number", required: true, dbField: "mileage" },
      { name: "pojemnosc", label: "Pojemność silnika (cm³)", type: "number", required: true, dbField: "engine_size" },
      {
        name: "paliwo",
        label: "Rodzaj paliwa",
        type: "select",
        options: ["Benzyna", "Diesel", "LPG", "Elektryczny", "Hybryda"],
        required: true,
        dbField: "fuel_type",
      },
      {
        name: "skrzynia",
        label: "Skrzynia biegów",
        type: "select",
        options: ["Manualna", "Automatyczna"],
        required: false,
        dbField: "transmission",
      },
      {
        name: "kolor",
        label: "Kolor",
        type: "select",
        options: [
          "Biały",
          "Czarny",
          "Srebrny",
          "Szary",
          "Czerwony",
          "Niebieski",
          "Zielony",
          "Żółty",
          "Brązowy",
          "Inny",
        ],
        required: false,
        dbField: "color",
      },
      {
        name: "stan",
        label: "Stan techniczny",
        type: "select",
        options: ["Bardzo dobry", "Dobry", "Zadowalający", "Do naprawy"],
        required: true,
        dbField: "condition_type",
      },
    ],
    Motocykle: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Aprilia",
          "BMW",
          "Ducati",
          "Harley-Davidson",
          "Honda",
          "Kawasaki",
          "KTM",
          "Suzuki",
          "Triumph",
          "Yamaha",
          "Pozostałe",
        ],
        required: true,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: true, dbField: "year" },
      { name: "przebieg", label: "Przebieg (km)", type: "number", required: true, dbField: "mileage" },
      { name: "pojemnosc", label: "Pojemność silnika (cm³)", type: "number", required: true, dbField: "engine_size" },
      {
        name: "typ",
        label: "Typ motocykla",
        type: "select",
        options: ["Sportowy", "Turystyczny", "Naked", "Cruiser", "Enduro", "Cross", "Skuter"],
        required: false,
        dbField: "motorcycle_type",
      },
    ],
    "Samochody Ciężarowe": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Isuzu",
          "Iveco",
          "Mercedes-Benz",
          "Ford",
          "Volkswagen",
          "MAN",
          "DAF",
          "Renault",
          "Scania",
          "Volvo",
          "Pozostałe",
        ],
        required: true,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: true, dbField: "year" },
      { name: "przebieg", label: "Przebieg (km)", type: "number", required: true, dbField: "mileage" },
      { name: "ladownosc", label: "Ładowność (kg)", type: "number", required: false, dbField: "payload" },
      {
        name: "typ_nadwozia",
        label: "Typ nadwozia",
        type: "select",
        options: ["Furgon", "Plandeka", "Chłodnia", "Cysterna", "Wywrotka", "Platforma"],
        required: false,
        dbField: "body_type",
      },
    ],
    Części: [
      { name: "marka", label: "Marka pojazdu", type: "text", required: false, dbField: "make" },
      { name: "model", label: "Model pojazdu", type: "text", required: false, dbField: "model" },
      { name: "rok", label: "Rok produkcji pojazdu", type: "number", required: false, dbField: "year" },
      {
        name: "stan",
        label: "Stan części",
        type: "select",
        options: ["Nowa", "Używana - bardzo dobra", "Używana - dobra", "Używana - do naprawy"],
        required: true,
        dbField: "condition_type",
      },
      { name: "numer_czesci", label: "Numer części", type: "text", required: false, dbField: "part_number" },
    ],
    Przyczepy: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: ["Niewiadów", "Tema", "Unitrailer", "Brenderup", "Pozostałe"],
        required: false,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: false, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
      { name: "ladownosc", label: "Ładowność (kg)", type: "number", required: false, dbField: "payload" },
      {
        name: "stan",
        label: "Stan techniczny",
        type: "select",
        options: ["Bardzo dobry", "Dobry", "Zadowalający", "Do naprawy"],
        required: true,
        dbField: "condition_type",
      },
    ],
    "Inne pojazdy": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: ["Yamaha", "Honda", "Kawasaki", "Can-Am", "Polaris", "Pozostałe"],
        required: false,
        dbField: "make",
      },
      { name: "model", label: "Model", type: "text", required: false, dbField: "model" },
      { name: "rok", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
      {
        name: "stan",
        label: "Stan techniczny",
        type: "select",
        options: ["Bardzo dobry", "Dobry", "Zadowalający", "Do naprawy"],
        required: true,
        dbField: "condition_type",
      },
    ],
  },
  "RTV/AGD": {
    Telewizory: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Samsung",
          "LG",
          "Sony",
          "Panasonic",
          "Philips",
          "Toshiba",
          "Sharp",
          "Grundig",
          "Hitachi",
          "Thomson",
          "Xiaomi",
          "Hisense",
          "TCL",
          "JVC",
          "Blaupunkt",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "przekatna", label: "Przekątna (cale)", type: "number", required: false, dbField: "screen_size" },
      {
        name: "rozdzielczosc",
        label: "Rozdzielczość",
        type: "select",
        options: ["HD Ready", "Full HD", "4K", "8K"],
        required: false,
        dbField: "resolution",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
      { name: "rok_produkcji", label: "Rok produkcji", type: "number", required: false, dbField: "year" },
    ],
    Kamery: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Sony",
          "Panasonic",
          "Canon",
          "Nikon",
          "GoPro",
          "DJI",
          "JVC",
          "Blackmagic",
          "Olympus",
          "Fujifilm",
          "Akaso",
          "YI",
          "Kodak",
          "SJCAM",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "typ",
        label: "Typ kamery",
        type: "select",
        options: ["Kamera sportowa", "Kamera cyfrowa", "Kamera analogowa", "Kamera bezpieczeństwa"],
        required: false,
        dbField: "camera_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    "Pralki/Suszarki": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Bosch",
          "Siemens",
          "Electrolux",
          "Samsung",
          "LG",
          "Whirlpool",
          "Amica",
          "Beko",
          "Indesit",
          "Candy",
          "Gorenje",
          "Hoover",
          "Hotpoint",
          "Miele",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "pojemnosc", label: "Pojemność (kg)", type: "number", required: false, dbField: "capacity" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Pralka", "Suszarka", "Pralko-suszarka"],
        required: false,
        dbField: "appliance_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Zmywarki: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Bosch",
          "Siemens",
          "Electrolux",
          "Whirlpool",
          "Beko",
          "Samsung",
          "Amica",
          "Indesit",
          "Candy",
          "Hotpoint",
          "Gorenje",
          "Miele",
          "Zanussi",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "pojemnosc", label: "Liczba kompletów", type: "number", required: false, dbField: "capacity" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Kuchenki: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Amica",
          "Bosch",
          "Electrolux",
          "Whirlpool",
          "Samsung",
          "Beko",
          "Gorenje",
          "Indesit",
          "Candy",
          "Hotpoint",
          "Mastercook",
          "Mora",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Gazowa", "Elektryczna", "Indukcyjna", "Mieszana"],
        required: false,
        dbField: "stove_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Piekarniki: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Bosch",
          "Samsung",
          "Electrolux",
          "Whirlpool",
          "Beko",
          "Amica",
          "Siemens",
          "Gorenje",
          "Indesit",
          "Candy",
          "Hotpoint",
          "Teka",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Elektryczny", "Gazowy", "Parowy"],
        required: false,
        dbField: "oven_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Lodówki: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Samsung",
          "LG",
          "Bosch",
          "Electrolux",
          "Whirlpool",
          "Beko",
          "Amica",
          "Gorenje",
          "Indesit",
          "Candy",
          "Miele",
          "Hisense",
          "Haier",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "pojemnosc", label: "Pojemność (l)", type: "number", required: false, dbField: "capacity" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Jednodrzwiowa", "Dwudrzwiowa", "Side by side", "French door"],
        required: false,
        dbField: "fridge_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Zamrażarki: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Electrolux",
          "Bosch",
          "Beko",
          "Whirlpool",
          "Amica",
          "Gorenje",
          "Liebherr",
          "Samsung",
          "Indesit",
          "Candy",
          "Hotpoint",
          "Haier",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "pojemnosc", label: "Pojemność (l)", type: "number", required: false, dbField: "capacity" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Szufladowa", "Skrzyniowa"],
        required: false,
        dbField: "freezer_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    Pozostałe: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Bosch",
          "Philips",
          "Tefal",
          "Braun",
          "Zelmer",
          "Moulinex",
          "Severin",
          "Russell Hobbs",
          "Amica",
          "Ravanson",
          "Clatronic",
          "Götze & Jensen",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
  },
  Elektronika: {
    Smartfony: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: ["Apple", "Samsung", "Huawei", "Xiaomi", "OnePlus", "Google", "Sony", "LG", "Nokia", "Pozostałe"],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "pamiec", label: "Pamięć wewnętrzna (GB)", type: "number", required: false, dbField: "storage" },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
      {
        name: "kolor",
        label: "Kolor",
        type: "select",
        options: ["Czarny", "Biały", "Srebrny", "Złoty", "Różowy", "Niebieski", "Czerwony", "Zielony", "Inny"],
        required: false,
        dbField: "color",
      },
    ],
    "Laptopy/Netbooki": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Acer",
          "Apple",
          "Asus",
          "Dell",
          "HP",
          "Lenovo",
          "Microsoft",
          "Samsung",
          "Sony",
          "Toshiba",
          "Pozostałe",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "procesor", label: "Procesor", type: "text", required: false, dbField: "processor" },
      { name: "ram", label: "Pamięć RAM (GB)", type: "number", required: false, dbField: "ram" },
      { name: "dysk", label: "Pojemność dysku (GB)", type: "number", required: false, dbField: "storage" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
    ],
    "Komputery Stacjonarne": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Acer",
          "Apple",
          "Asus",
          "Dell",
          "HP",
          "Huawei",
          "Lenovo",
          "Microsoft",
          "Samsung",
          "Sony",
          "Toshiba",
          "Inne marki",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "procesor", label: "Procesor", type: "text", required: false, dbField: "processor" },
      { name: "ram", label: "Pamięć RAM (GB)", type: "number", required: false, dbField: "ram" },
      { name: "dysk", label: "Pojemność dysku (GB)", type: "number", required: false, dbField: "storage" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
    ],
    "Tablety/Palmtopy": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Acer",
          "Apple",
          "Asus",
          "Dell",
          "HP",
          "Huawei",
          "Lenovo",
          "Microsoft",
          "Samsung",
          "Sony",
          "Toshiba",
          "Inne marki",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      { name: "przekatna", label: "Przekątna ekranu (cale)", type: "number", required: false, dbField: "screen_size" },
      { name: "pamiec", label: "Pamięć wewnętrzna (GB)", type: "number", required: false, dbField: "storage" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
    ],
    Smartwatche: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: ["Apple", "Samsung", "Huawei", "Garmin", "Fitbit", "Amazfit", "Polar", "Suunto"],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
      { name: "gwarancja", label: "Gwarancja", type: "checkbox", required: false, dbField: "warranty_months" },
    ],
    "Urządzenia Stacjonarne": [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: ["Apple", "Dell", "HP", "Lenovo", "Acer", "Asus", "Microsoft"],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: true, dbField: "model" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
    ],
    Akcesoria: [
      {
        name: "marka",
        label: "Marka",
        type: "select",
        options: [
          "Logitech",
          "Microsoft",
          "Razer",
          "Corsair",
          "SteelSeries",
          "Asus",
          "Acer",
          "Dell",
          "HP",
          "Lenovo",
          "Inne marki",
        ],
        required: true,
        dbField: "brand",
      },
      { name: "model", label: "Model", type: "text", required: false, dbField: "model" },
      {
        name: "typ",
        label: "Typ akcesoria",
        type: "select",
        options: ["Mysz", "Klawiatura", "Słuchawki", "Kamera", "Mikrofon", "Inne"],
        required: false,
        dbField: "accessory_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: false,
        dbField: "condition_type",
      },
    ],
  },
  Moda: {
    Sukienki: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "34", "36", "38", "40", "42", "44", "46", "48"],
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
      {
        name: "dlugosc",
        label: "Długość",
        type: "select",
        options: ["Mini", "Midi", "Maxi"],
        required: false,
        dbField: "dress_length",
      },
    ],
    Buty: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"],
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      {
        name: "typ",
        label: "Typ butów",
        type: "select",
        options: ["Sportowe", "Eleganckie", "Casual", "Sandały", "Kozaki", "Szpilki", "Baleriny"],
        required: false,
        dbField: "shoe_type",
      },
    ],
    Spódnice: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "34", "36", "38", "40", "42", "44", "46", "48"],
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
    ],
    Koszule: [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "34", "36", "38", "40", "42", "44", "46", "48"],
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
    ],
    "T-shirty i Polówki": [
      { name: "marka", label: "Marka", type: "text", required: false, dbField: "brand" },
      {
        name: "rozmiar",
        label: "Rozmiar",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "34", "36", "38", "40", "42", "44", "46", "48"],
        required: true,
        dbField: "size",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: ["Nowy", "Używany - jak nowy", "Używany - dobry", "Używany - widoczne ślady użytkowania"],
        required: true,
        dbField: "condition_type",
      },
      { name: "kolor", label: "Kolor", type: "text", required: false, dbField: "color" },
      { name: "material", label: "Materiał", type: "text", required: false, dbField: "material" },
    ],
  },
  Nieruchomości: {
    Domy: [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      { name: "liczba_pokoi", label: "Liczba pokoi", type: "number", required: false, dbField: "rooms" },
      { name: "pietro", label: "Piętro", type: "number", required: false, dbField: "floor" },
      { name: "rok_budowy", label: "Rok budowy", type: "number", required: false, dbField: "year_built" },
      { name: "umeblowane", label: "Umeblowane", type: "checkbox", required: false, dbField: "furnished" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: [
          "Do remontu",
          "Do odświeżenia",
          "Do zamieszkania",
          "Stan deweloperski",
          "Stan surowy otwarty",
          "Stan surowy zamknięty",
          "Po generalnym remoncie",
        ],
        required: true,
        dbField: "condition_type",
      },
      {
        name: "typ_domu",
        label: "Typ domu",
        type: "select",
        options: ["Wolnostojący", "Bliźniak", "Szeregowy", "Gospodarczy"],
        required: false,
        dbField: "house_type",
      },
      { name: "dzialka", label: "Powierzchnia działki (m²)", type: "number", required: false, dbField: "plot_area" },
    ],
    Mieszkania: [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      { name: "liczba_pokoi", label: "Liczba pokoi", type: "number", required: false, dbField: "rooms" },
      { name: "pietro", label: "Piętro", type: "number", required: false, dbField: "floor" },
      { name: "rok_budowy", label: "Rok budowy", type: "number", required: false, dbField: "year_built" },
      { name: "umeblowane", label: "Umeblowane", type: "checkbox", required: false, dbField: "furnished" },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: [
          "Do remontu",
          "Do odświeżenia",
          "Do zamieszkania",
          "Stan deweloperski",
          "Stan surowy otwarty",
          "Stan surowy zamknięty",
          "Po generalnym remoncie",
        ],
        required: true,
        dbField: "condition_type",
      },
      { name: "balkon", label: "Balkon", type: "checkbox", required: false, dbField: "has_balcony" },
      { name: "winda", label: "Winda", type: "checkbox", required: false, dbField: "has_elevator" },
    ],
    Działki: [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      {
        name: "przeznaczenie",
        label: "Przeznaczenie",
        type: "select",
        options: ["Budowlana", "Rolna", "Leśna", "Rekreacyjna", "Inwestycyjna"],
        required: true,
        dbField: "plot_purpose",
      },
      {
        name: "ksztalt",
        label: "Kształt działki",
        type: "select",
        options: ["Prostokątna", "Kwadratowa", "Nieregularna", "Narożna"],
        required: false,
        dbField: "plot_shape",
      },
      { name: "media", label: "Dostęp do mediów", type: "checkbox", required: false, dbField: "has_utilities" },
    ],
    Lokale: [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      { name: "pietro", label: "Piętro", type: "number", required: false, dbField: "floor" },
      { name: "rok_budowy", label: "Rok budowy", type: "number", required: false, dbField: "year_built" },
      { name: "umeblowane", label: "Umeblowane", type: "checkbox", required: false, dbField: "furnished" },
      {
        name: "typ_lokalu",
        label: "Typ lokalu",
        type: "select",
        options: ["Biurowy", "Handlowy", "Usługowy", "Gastronomiczny", "Magazynowy"],
        required: true,
        dbField: "commercial_type",
      },
      {
        name: "stan",
        label: "Stan",
        type: "select",
        options: [
          "Do remontu",
          "Do odświeżenia",
          "Do zamieszkania",
          "Stan deweloperski",
          "Stan surowy otwarty",
          "Stan surowy zamknięty",
          "Po generalnym remoncie",
        ],
        required: true,
        dbField: "condition_type",
      },
    ],
    "Garaże/Magazyny": [
      { name: "powierzchnia", label: "Powierzchnia (m²)", type: "number", required: true, dbField: "square_meters" },
      { name: "rok_budowy", label: "Rok budowy", type: "number", required: false, dbField: "year_built" },
      {
        name: "typ",
        label: "Typ",
        type: "select",
        options: ["Garaż", "Magazyn", "Piwnica", "Strych"],
        required: true,
        dbField: "storage_type",
      },
      { name: "wysokosc", label: "Wysokość (m)", type: "number", required: false, dbField: "height" },
    ],
  },
} as const
