export const businessCategories = [
    "Sklep detaliczny",
    "Sklep internetowy",
    "Supermarket",
    "Hurtownia",
    "Usługi",
    "Rozrywka",
    "Transport/Logistyka",
    "Klub nocny",
    "Sanatorium",
    "Piekarnia",
    "Centrum zdrowia",
    "Kino/Teatr",
    "Miasto",
    "Strona/Portal",
    "Obiekt/Placówka",
    "Restauracja/Bar/Kawiarnia",
    "Blog",
    "Gry",
    "Turystyka/Rekreacja",
    "Edukacja",
    "Galeria",
    "Finanse/Ubezpieczenia",
    "Bank",
    "Uroda/Zdrowie/Relaks",
    "Nieruchomości",
    "Reklama/Biznes",
    "Druk/Publikacje",
    "Salon samochodowy/Targ",
    "Noclegi",
    "Kasyno",
    "Fundacja",
    "Telekomunikacja/Internet",
    "Fan Klub",
    "Organizacja",
    "Instytucja/Urząd",
    "Znana osoba",
  ]