-- Add likes column to ads table if it doesn't exist
ALTER TABLE ads ADD COLUMN IF NOT EXISTS likes INT NOT NULL DEFAULT 0;

-- Create ad_likes table if it doesn't exist
CREATE TABLE IF NOT EXISTS ad_likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  ad_id INT NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE,
  UNIQUE KEY (user_id, ad_id)
);

-- Add columns for specific categories
-- For real estate
ALTER TABLE ads ADD COLUMN IF NOT EXISTS square_meters FLOAT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS rooms INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS floor INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS total_floors INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS year_built INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS heating_type VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS has_balcony BOOLEAN DEFAULT FALSE;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS has_garage BOOLEAN DEFAULT FALSE;

-- For vehicles
ALTER TABLE ads ADD COLUMN IF NOT EXISTS make VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS model VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS year INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS mileage INT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS transmission VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS engine_size FLOAT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS color VARCHAR(50);

-- For electronics
ALTER TABLE ads ADD COLUMN IF NOT EXISTS brand VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS condition_type VARCHAR(50);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS warranty_months INT;

-- For jobs
ALTER TABLE ads ADD COLUMN IF NOT EXISTS job_type VARCHAR(50);