name: Deploy to CyberFolks

on:
  push:
    branches:
      - main  # lub 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build && npm run export

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CF_HOST }}
          username: ${{ secrets.CF_USER }}
          key: ${{ secrets.CF_SSH_KEY }}
          source: out/
          target: domains/gotpage.pl/public_html
