name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 222 gotpage.pl >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 222 gotpage.pl >> ~/.ssh/known_hosts
          ssh -v -i ~/.ssh/id_ed25519 -p 222 biycgepwzk@gotpage.pl << 'EOF'
            cd domains/gotpage.pl/public_html
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart gotpage
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
