name: Deploy to CyberFolks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Upload app to CyberFolks
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CF_HOST }}
          username: ${{ secrets.CF_USER }}
          key: ${{ secrets.CF_SSH_KEY }}
          port: 222
          source: |
            .next
            public
            package.json
            package-lock.json
            next.config.js
          target: /home/${{ secrets.CF_USER }}/domains/gotpage.pl/public_html

      - name: Restart PM2 on CyberFolks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CF_HOST }}
          username: ${{ secrets.CF_USER }}
          key: ${{ secrets.CF_SSH_KEY }}
          port: 222
          script: |
            cd /home/${{ secrets.CF_USER }}/domains/gotpage.pl/public_html
            pm2 restart gotpage || pm2 start npm --name gotpage -- start -- -p 4001
