name: Simple Deploy to CyberFolks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload source files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CF_HOST }}
          username: ${{ secrets.CF_USER }}
          key: ${{ secrets.CF_SSH_KEY }}
          port: 222
          source: .
          target: /home/${{ secrets.CF_USER }}/domains/gotpage.pl/public_html

      - name: Run npm ci + restart app via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CF_HOST }}
          username: ${{ secrets.CF_USER }}
          key: ${{ secrets.CF_SSH_KEY }}
          port: 222
          script: |
            cd /home/${{ secrets.CF_USER }}/domains/gotpage.pl/public_html
            npm ci
            pm2 restart gotpage || pm2 start npm --name gotpage -- start -- -p 4000
