name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then echo "❌ Missing secret: SSH_HOST"; exit 1; fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then echo "❌ Missing secret: SSH_USER"; exit 1; fi
          if [ -z "${{ secrets.SSH_KEY }}" ]; then echo "❌ Missing secret: SSH_KEY"; exit 1; fi
          if [ -z "${{ secrets.SSH_PORT }}" ]; then echo "❌ Missing secret: SSH_PORT"; exit 1; fi
          if [ -z "${{ secrets.REMOTE_PATH }}" ]; then echo "❌ Missing secret: REMOTE_PATH"; exit 1; fi
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Rebuild sharp for Linux
        run: npm rebuild sharp --platform=linux --arch=x64

      - name: Build Next.js app
        run: npm run build

      - name: Archive files
        run: |
          tar -czf deploy.tar.gz \
            .next \
            public \
            package.json \
            package-lock.json \
            next.config.mjs \
            ecosystem.config.js

      - name: Copy deploy.tar.gz to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tar.gz"
          target: "${{ secrets.REMOTE_PATH }}"

      - name: Remote deploy & restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            rm -rf .next
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            npm install --omit=dev
            pm2 restart ecosystem.config.js --update-env
            pm2 save
